apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
spec:
  selector:
    app: devsecops
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # Puerto alto accesible en los nodos
