name: Build, Scan & Publish Docker Image

on:
  push:
    branches:
      - master  # O la rama que uses para producción

jobs:
  build_scan_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devsecops-pipeline:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.13.0



        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/devsecops-pipeline:latest
          format: 'table'
          exit-code: '1'   # Fallará el job si detecta vulnerabilidades
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devsecops-pipeline:latest
