name: Build, Scan & Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_scan_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set lowercase owner variable
        run: echo "REPO_OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER_LC }}/devsecops-pipeline:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ghcr.io/${{ env.REPO_OWNER_LC }}/devsecops-pipeline:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER_LC }}/devsecops-pipeline:latest
